-- Generated by spritter v1.8.0 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 0 },
  ["file_count"] = 1,
  ["height"] = 400,
  ["line_length"] = 8,
  ["lines_per_file"] = 8,
  ["scale"] = 0.5,
  ["shift"] = {0 / 64, 0 / 64},
  ["sprite_count"] = 64,
  ["width"] = 400,
}
